#! /usr/bin/env python

from OVarCall.runFilter import *
import argparse

#
# top level parser
#
parser = argparse.ArgumentParser(prog="OVarFilter")
parser.add_argument("--version", action="version", version="OVarFilter-0.1.1")

parser.add_argument('-1', '--bam1', help='1st bam file ( disease )', type=str, default=None, required=True)
parser.add_argument('-2', '--bam2', help='2nd bam file ( control )', type=str, default=None, required=True)
parser.add_argument('-i', '--input', help='Input vcf file', type=str, default=None, required=True)
parser.add_argument('-o', '--output', help='Output text file', type=str, default=None, required=True)
parser.add_argument('-r', '--ref_fa', help='Reference genome in fasta format', type=str, default=None, required=True)
parser.add_argument('-p', '--parameter_settings', help="parameter settings path (.ini) ", type=str, default=None,required=True)
parser.add_argument('-f',  '--filter_pileup', help=" exec filer after pileup", dest='filterPileup', action='store_true',default=False)
parser.add_argument('-l', '--log_level', help="Logging level", type=str, default='INFO')
parser.add_argument('-a', '--annovar_format', dest='annovarFile', action='store_true',default=False)

####################
  #
  # logging setup
  #
  # Level     function            value    description
  # CRITICAL  logging.critical()  50      Output only critical errors
  # ERROR     logging.error()     40      Output errors
  # WARNING   logging.warning()   30      Output warnings
  # INFO      logging.info()      20      Output information
  # DEBUG     logging.debug()     10      Output debug information
  # NOTSET                        0       Output all
  #
####################
args = parser.parse_args()

runOVarFilter(args)